<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\rdc-bas\rdc-bas.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RPIDBClock.LCD</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IntermediateOutputPath>..\..\Obj\$(Configuration)Lcd</IntermediateOutputPath>
    <OutputPath>..\..\Bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Device.Gpio" Version="3.2.0" />
  </ItemGroup>

</Project>
