<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RPIDBClock.LCD</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IntermediateOutputPath>..\..\Obj\$(Configuration)</IntermediateOutputPath>
    <OutputPath>..\..\Bin\$(Configuration)\Lcd</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Device.Gpio" Version="3.2.0" />
  </ItemGroup>

</Project>
