<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RPIDBClock</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IntermediateOutputPath>..\..\Obj\$(Configuration)Bas</IntermediateOutputPath>
    <OutputPath>..\..\Bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

</Project>
