<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\rdc-rtc\rdc-rtc.csproj" />
    <ProjectReference Include="..\rdc-lcd\rdc-lcd.csproj" />
    <ProjectReference Include="..\rdc-net\rdc-net.csproj" />
    <ProjectReference Include="..\rdc-svc\rdc-svc.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RPIDBClock.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <IntermediateOutputPath>..\..\Obj\$(Configuration)Tests</IntermediateOutputPath>
    <OutputPath>..\..\Bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
